### ISSUE TITLE
Report will not generated

### ISSUE THREAD

**Issue by mmarkert** [Qumulo/daily-storage-reports-app#10]
Hi,
the report is not created while pressing the "Email Report" button:

...
192.168.10.11 - - [29/Oct/2018 09:16:22] "GET /get-data-json?d=iops&path=/media&start_date=2018-10-27&end_date=2018-10-29&cluster_name=blackhole HTTP/1.1" 200 -
192.168.10.11 - - [29/Oct/2018 09:16:22] "GET /get-data-json?d=file_iops&path=/media&start_date=2018-10-27&end_date=2018-10-29&cluster_name=blackhole HTTP/1.1" 200 -
192.168.10.11 - - [29/Oct/2018 09:16:22] "GET /get-data-json?d=path_stats&path=/media&start_date=2018-10-27&end_date=2018-10-29&cluster_name=blackhole HTTP/1.1" 200 -
Send email report
Launch phantomjs

[root@hubble ~]# ps -affe | grep phantomjs
root      1050   798  0 09:16 pts/0    00:00:00 phantomjs phantom-screenshot.js to=mmarkert@arri.de&cluster_name=blackhole&path=%2Fmedia&start_date=2018-10-27&end_date=2018-10-29 qumulo-storage-report-blackhole-_media-20181027-20181029.pdf

Killing the process returns:
...
phantomjs complete
192.168.10.11 - - [29/Oct/2018 09:16:50] "GET /email?to=mmarkert@arri.de&cluster_name=blackhole&path=%2Fmedia&start_date=2018-10-27&end_date=2018-10-29 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/daily_storage_reports/app.py", line 450, in send_email
    with open(pdf_name, "rb") as fil:
IOError: [Errno 2] No such file or directory: u'qumulo-storage-report-blackhole-_media-20181027-20181029.pdf'

Kind regards,
Martin

**Comment by mmarkert** [comment]
Fix: full url required in config.json, added "http://"
