### ISSUE TITLE
Error: Pulling csv data for: iops_by_path

### ISSUE THREAD

**Issue by mmarkert** [Qumulo/daily-storage-reports-app#12]
Hi Tommy,
today I have updated the application via git and now the following error occurs:

```
[root@hubble ~]# /root/.bash_profile; cd /opt/daily_storage_reports; python app.py --op api_pull --api_data iops_by_path
2020-04-09 13:41:28 - Pulling csv data for: iops_by_path
Traceback (most recent call last):
  File "app.py", line 546, in <module>
    apicsv.get_data(api_call)
  File "/opt/daily_storage_reports/apitocsv.py", line 83, in get_data
    f(api_call_name)
  File "/opt/daily_storage_reports/apitocsv.py", line 199, in get_iops_by_path
    res = self.qumulo_api_call(iops_get_func)
  File "/opt/daily_storage_reports/apitocsv.py", line 63, in qumulo_api_call
    res = f(**kwargs)
  File "/usr/lib/python2.7/site-packages/qumulo/rest_client.py", line 97, in wrapper
    self.client.handle_request_error(e)
  File "/usr/lib/python2.7/site-packages/qumulo/rest_client.py", line 95, in wrapper
    **kwargs)
  File "/usr/lib/python2.7/site-packages/qumulo/rest/analytics.py", line 29, in iops_get
    return request.rest_request(conninfo, credentials, method, str(uri))
  File "/usr/lib/python2.7/site-packages/qumulo/lib/request.py", line 416, in rest_request
    rest.get_response()
  File "/usr/lib/python2.7/site-packages/qumulo/lib/request.py", line 376, in get_response
    self.response_obj)
qumulo.lib.request.RequestError: Error 404: unknown: Dev error: No json error response.
```

**Comment by TommyUnger** [comment]
Resolved the issue. It was an API change that needed to be accounted for in this script.
